# Generated by Django 5.1 on 2024-08-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='relevant',
            field=models.BooleanField(default=False),
        ),
    ]
